# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brandon Moore
email: moore.3071@osu.edu
description: > # this means to ignore newlines until "baseurl:"
  My name is Brandon Moore. I am an alumnus from Ohio State University and president emeritus of the Open Source Club at OSU. I am a strong proponent of open source software and best practices in development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://moore3071.github.io" # the base hostname & protocol for your site
github_username:  moore3071

# Build settings
markdown: kramdown
